export const professionDialogue = {
  farmer: [
    "The crops are growing well today!",
    "Have you seen my wheat fields?",
    "A good harvest means a good life!",
    "I planted carrots this morning.",
    "The soil is rich here in the village.",
    "Rain is coming, good for the crops!",
    "I've been farming since I was a child.",
    "The pumpkins are nearly ready!",
    "Beetroot stew tonight, care to join?",
    "I traded my best wheat this morning.",
    "The crows keep eating my seeds!",
    "Nothing beats freshly baked bread.",
    "I woke up before sunrise to water the fields.",
    "The compost pile is working wonders!",
    "A farmer's work is never truly done.",
    "I found a golden carrot in the field today!",
    "The harvest festival is coming soon!",
    "I need more bonemeal for these crops.",
    "My grandmother taught me to farm.",
    "Have you tried my homemade carrot soup?",
    "The scarecrow keeps the crows away mostly.",
    "I trade with the fletcher for seeds sometimes.",
    "My hoe broke again this morning!",
    "I planted a whole row of melons today.",
    "The fields look golden this time of year.",
  ],
  fisherman: [
    "The fish are biting today!",
    "I caught a salmon this morning!",
    "The river is calm, perfect for fishing.",
    "Need any fresh fish? I have plenty!",
    "A quiet day by the water is all I need.",
    "I once caught a fish this big, I swear!",
    "The lake is full of cod today.",
    "I've been fishing since I could walk.",
    "Nothing beats the smell of the river.",
    "I found a treasure chest while fishing!",
    "The best fishing spots are my secret.",
    "I use special bait I make myself.",
    "A storm is coming, rough seas ahead.",
    "I traded three salmon for emeralds today.",
    "The moonlight makes for great night fishing.",
    "I spotted a squid near the docks!",
    "Fishing teaches you patience above all.",
    "The river provides everything I need.",
    "I repaired my fishing rod this morning.",
    "One day I'll catch the legendary fish!",
    "I saw a dolphin near the shore today!",
    "My net caught three fish at once!",
    "The tide is just right for fishing today.",
    "I traded my rod enchantment for emeralds.",
    "A fisherman never reveals his best spot.",
  ],
  shepherd: [
    "Have you seen my sheep around?",
    "Fresh wool, just sheared this morning!",
    "The meadows are beautiful today.",
    "I have the finest wool in the village!",
    "My sheep wandered off again...",
    "I dyed some wool red this afternoon.",
    "Counting sheep helps me sleep at night.",
    "I have twelve sheep and know them all by name.",
    "The lambs were born just last week!",
    "Wool keeps the whole village warm in winter.",
    "I make my own dyes from flowers.",
    "The sheep love the clover fields.",
    "I lost a sheep to wolves last night...",
    "My favorite sheep is named Snowball.",
    "Shearing season is my favorite time of year.",
    "I traded a full stack of wool today!",
    "The hills are perfect for grazing.",
    "I could use some help herding today.",
    "Blue wool is the hardest to dye.",
    "A shepherd's crook is my most prized tool.",
    "I found a rare black sheep this morning!",
    "The wool market is booming right now.",
    "I need more dye to finish my order.",
    "My youngest lamb follows me everywhere.",
    "I made a new wool blanket last night.",
  ],
  fletcher: [
    "Need arrows? I have the best stock!",
    "A fine bow needs fine arrows.",
    "I crafted twenty arrows this morning.",
    "The wood grain on this bow is perfect.",
    "A fletcher's work is never done!",
    "I use only the finest feathers for fletching.",
    "That bow took me three days to string.",
    "I can craft a crossbow in under an hour.",
    "My arrows fly straighter than anyone else's.",
    "The hunters love my tipped arrows.",
    "I source my wood from the dark oak forest.",
    "A bowstring must be just tight enough.",
    "I traded my best crossbow this morning.",
    "Nothing protects the village like good arrows.",
    "I taught myself to fletch as a teenager.",
    "I have arrows for every occasion!",
    "My quivers are the sturdiest around.",
    "I need more flint from the gravel beaches.",
    "A good fletcher never misses a detail.",
    "I made fifty arrows before breakfast!",
    "I just restocked my arrow supply.",
    "A crossbow needs more maintenance than a bow.",
    "I traded tipped arrows for a good price today.",
    "The feathers I use come from jungle parrots.",
    "I can fletch an arrow in under a minute.",
  ],
  librarian: [
    "Knowledge is the greatest treasure!",
    "Have you read any good books lately?",
    "I found a rare enchanted tome today.",
    "The library grows with every trade.",
    "Words hold more power than swords.",
    "I've read every book twice over.",
    "The ancient texts speak of great wonders.",
    "I organize my books by enchantment type.",
    "A library is a village's greatest asset.",
    "I stayed up all night reading last night.",
    "This tome is written in a strange language.",
    "I trade knowledge for emeralds gladly.",
    "Every book tells a different story.",
    "I discovered a new enchantment today!",
    "The shelves are running out of space.",
    "I wrote my own book about village history.",
    "Knowledge shared is knowledge doubled.",
    "I need more paper for my collection.",
    "The best adventures are found in books.",
    "I once found a book written by a wizard!",
    "I found a Silk Touch tome this morning!",
    "The enchanting table hums when I walk by.",
    "I traded three books before noon today.",
    "I am writing a book about village history.",
    "Every enchantment tells a story of its own.",
  ],
  cartographer: [
    "I mapped three new caves yesterday!",
    "Every path leads to a new discovery.",
    "The world is bigger than most think.",
    "I need more paper for my maps!",
    "There are uncharted lands to the east.",
    "I discovered a jungle temple last week!",
    "My maps have led many travelers safely.",
    "The ocean monument is marked on this map.",
    "I use a compass and the stars to navigate.",
    "Every village deserves a proper map.",
    "I charted the entire desert biome myself.",
    "There's a stronghold somewhere to the north.",
    "My maps are accurate to the last block.",
    "I once got lost making a map. Ironic.",
    "The world map is nearly complete!",
    "I marked every dungeon I've ever found.",
    "Treasure maps are my specialty.",
    "I need a boat to map the islands.",
    "The nether is too dangerous to map alone.",
    "Every explorer needs one of my maps!",
    "I spotted a woodland mansion to the west!",
    "My latest map sold for twenty emeralds.",
    "I use the sun and stars to stay on course.",
    "The ocean is the hardest terrain to map.",
    "I found an ancient buried map in a chest!",
  ],
  cleric: [
    "May the light protect you, traveler.",
    "I sense dark magic nearby... beware.",
    "The potions are freshly brewed!",
    "Blessings upon you, wanderer.",
    "The stars spoke to me last night.",
    "I brewed a strength potion this morning.",
    "The undead fear the light I carry.",
    "Ender pearls hold mysterious energy.",
    "I have studied magic my entire life.",
    "The brewing stand never rests.",
    "I sense a zombie nearby... stay close.",
    "My potions have saved many lives.",
    "The nether wart grows well this season.",
    "I pray for the village every morning.",
    "Dark times are coming, I can feel it.",
    "Glowstone dust is hard to come by.",
    "I traded a potion of healing today.",
    "The spirits guide my every brew.",
    "Even the Ender Dragon fears the light.",
    "May your journey be safe, friend.",
    "I sensed dark energy near the graveyard.",
    "My latest potion batch turned out perfectly.",
    "The end portal calls to me in my dreams.",
    "I collect Ender pearls for my research.",
    "I once brewed a potion of invisibility!",
  ],
  armorer: [
    "My armor will protect you in battle!",
    "The finest steel in all the land!",
    "I've been at the forge since dawn.",
    "A knight is only as strong as his armor.",
    "Need repairs? I'm your person!",
    "I hammered out a full set of iron today.",
    "Diamond armor is my masterpiece.",
    "The forge burns hot today.",
    "I learned smithing from my father.",
    "No dent is too big for me to fix!",
    "I use only the purest iron ingots.",
    "Chain mail is trickier than it looks.",
    "I traded a full armor set this morning.",
    "My anvil has seen a thousand repairs.",
    "A good breastplate lasts a lifetime.",
    "The heat of the forge keeps me warm.",
    "I finished a helmet just before sunrise.",
    "Protection enchantments pair well with my work.",
    "I once made armor for a king!",
    "Every warrior deserves good protection.",
    "I just finished a full netherite set!",
    "The blast furnace runs faster than a furnace.",
    "I repaired a cracked chestplate today.",
    "My armor has saved many adventurers.",
    "Iron is good but diamonds are better.",
  ],
  weaponsmith: [
    "A sharp blade keeps enemies at bay!",
    "This sword took three days to forge.",
    "No weapon leaves my shop unsharpened.",
    "I can craft a blade for any warrior.",
    "The ringing of the anvil soothes me.",
    "I forged my first sword at age twelve.",
    "A dull blade is more dangerous than none.",
    "I use enchanted grindstones to sharpen.",
    "This axe could fell an oak in one swing.",
    "I traded a diamond sword today!",
    "Every blade tells a story of its own.",
    "I temper my steel in ice cold water.",
    "The best swords are balanced perfectly.",
    "I once made a sword that never dulled!",
    "A warrior is only as good as their blade.",
    "I polish every weapon before trading.",
    "The sound of the forge is music to me.",
    "I can make any weapon you need.",
    "My blades have protected this village.",
    "A sharp sword and courage, that's all you need!",
    "I sharpened a diamond axe this morning.",
    "My best sword sold for thirty emeralds.",
    "I can feel the balance of a blade instantly.",
    "A good sword needs the right weight.",
    "I once forged a weapon for a legendary hero!",
  ],
  toolsmith: [
    "A good tool makes any job easier!",
    "I sharpened twenty pickaxes today.",
    "Without tools, nothing gets built.",
    "Need a new shovel? I just made some!",
    "Quality tools, fair prices!",
    "I made a diamond pickaxe this morning.",
    "Every miner needs a reliable pick.",
    "I craft tools that last for years.",
    "The right tool makes all the difference.",
    "I traded three hoes for emeralds today.",
    "I can repair any broken tool you have.",
    "My axes are the sharpest in the village.",
    "I use special alloys for extra durability.",
    "A good shovel is worth its weight in gold.",
    "I've supplied every builder in the village.",
    "Fortune pickaxes are my specialty.",
    "I wake up early to get to the forge first.",
    "A craftsman is proud of every tool made.",
    "I once made an unbreakable hoe!",
    "The miners keep me busier than ever.",
    "I just enchanted a pickaxe with Fortune III.",
    "My shovels are the fastest in the land.",
    "I craft tools that outlast the competition.",
    "I traded an efficiency axe today.",
    "A broken tool is a sad sight to see.",
  ],
  butcher: [
    "Fresh meat, just prepared this morning!",
    "The finest cuts in the village!",
    "I have pork chops and beef today.",
    "A hearty meal keeps you strong!",
    "Nothing goes to waste in my shop.",
    "I smoked a rack of ribs last night.",
    "The best stew in the village, right here!",
    "I traded cooked chicken for emeralds today.",
    "My cleaver is always sharp and ready.",
    "Fresh mutton, just in from the shepherd!",
    "I've been a butcher my whole life.",
    "Every cut of meat is prepared with care.",
    "Rabbit stew is today's special!",
    "I source only the finest livestock.",
    "My smoker runs day and night.",
    "A full belly makes for a happy villager.",
    "I make the best dried beef in the region.",
    "The hunters bring me game every morning.",
    "Cooked porkchop is my personal favorite.",
    "Come back tomorrow for the weekly special!",
    "I traded smoked salmon this morning.",
    "My secret spice mix is a family recipe.",
    "The farmers keep me well supplied.",
    "I have the sharpest cleaver in the village.",
    "Nothing goes better with bread than my beef.",
  ],
  leatherworker: [
    "Finest leather goods in the region!",
    "I tanned three hides this morning.",
    "A good saddle lasts a lifetime.",
    "Leather armor is lighter than you think!",
    "Need boots? I have your size!",
    "I dyed a set of red leather armor today.",
    "A leather satchel for every adventurer!",
    "I source my hides from the butcher.",
    "Good leather takes time to tan properly.",
    "I crafted a horse saddle before sunrise.",
    "My boots have walked a thousand miles.",
    "Leather working is a dying art, I fear.",
    "I made a beautiful brown tunic today.",
    "Every piece of leather has potential.",
    "I use a secret tanning formula.",
    "My gloves keep the forge workers safe.",
    "I traded two saddles for emeralds today.",
    "The smell of fresh leather is my favorite.",
    "I once made armor for the village chief!",
    "A good leather belt holds everything together.",
    "I just dyed a full set of blue leather armor.",
    "My saddles are famous across the region.",
    "I traded three sets of armor today.",
    "A good leather vest lasts many adventures.",
    "I use only the finest cowhide for my work.",
  ],
  mason: [
    "Every stone tells a story.",
    "I carved this pillar myself!",
    "Good stonework lasts a thousand years.",
    "The quarry has the finest granite today.",
    "Building with stone is an art form.",
    "I laid the cobblestone paths in this village.",
    "A mason's chisel is their best friend.",
    "I polished a set of diorite blocks today.",
    "I built the village well with my own hands.",
    "Stone bricks are my specialty.",
    "The quarry provides endless material.",
    "I traded cut sandstone this morning.",
    "Every crack in a wall bothers me deeply.",
    "I can build anything from stone!",
    "The village walls will stand forever.",
    "I carve patterns into every stone I cut.",
    "Andesite, granite, diorite — I love them all.",
    "A solid foundation is everything.",
    "I once built a stone castle by myself!",
    "My stonecutter blade is always sharp.",
    "I just carved a decorative arch today.",
    "Polished granite is my favorite material.",
    "The new village wall is coming along nicely.",
    "I traded a full stack of stone bricks today.",
    "My chisel has carved a thousand blocks.",
  ],
  nitwit: [
    "Ummmm... hello?",
    "I like green things.",
    "Did you see that cloud? It was fluffy.",
    "I forgot what I was doing.",
    "Hmmmm...",
    "I tried to fish with a stick once.",
    "Sometimes I just stand here and think.",
    "I counted to ten today! Well... mostly.",
    "I found a pretty rock this morning!",
    "What was I saying again?",
    "I waved at a cow and it ignored me.",
    "The sky is very sky-colored today.",
    "I tried to trade once. It didn't work.",
    "I like watching the clouds go by.",
    "Do you think sheep dream about grass?",
    "I tried to build something. It fell down.",
    "Someone told me to get a job. I forgot.",
    "I had a great idea earlier. Now it's gone.",
    "I think I left something somewhere.",
    "La la la... what were we talking about?",
    "I tried to trade a dirt block once.",
    "Is it morning or evening? I lost track.",
    "I sat on a fence for an hour today.",
    "Someone gave me bread. I forgot to eat it.",
    "I think I saw a dragon... or was it a cloud?",
  ],
  unemployed: [
    "Looking for work these days...",
    "Perhaps I'll find a job block soon.",
    "Times are tough without a trade.",
    "Do you need any help with anything?",
    "I'm still figuring out my path.",
    "I applied to be a librarian once.",
    "Maybe the armorer needs an apprentice?",
    "I sweep the village paths for now.",
    "A job would change everything for me.",
    "I'm good with my hands, just need a chance.",
    "I heard the toolsmith is hiring!",
    "Without a job block, I have no trade.",
    "I used to work on a farm far away.",
    "Every day I look for an opportunity.",
    "The village always needs more workers!",
    "I almost got a job at the library today.",
    "Perhaps farming is the path for me.",
    "I'll find my calling eventually.",
    "Hard times don't last, hard work does.",
    "A new day brings a new opportunity!",
    "I heard the librarian needs an assistant.",
    "I tried farming once. The crops died.",
    "Maybe I should learn to fish instead.",
    "I swept the entire village square today!",
    "One day I will find my true calling.",
  ],
};

export function getDialogueLine(label) {
  const key = label.toLowerCase();
  const lines = professionDialogue[key] ?? professionDialogue["unemployed"];
  return lines[Math.floor(Math.random() * lines.length)];
}