export const hostileDialogue = {
  illager: [
    "You dare enter our territory?!",
    "The village will fall before us!",
    "We serve the Pillager captain!",
    "Leave now while you still can!",
    "You will regret crossing us!",
    "The raid begins at nightfall!",
    "No villager is safe from us!",
    "Our captain commands your defeat!",
    "We have raided stronger villages!",
    "The Illager army is unstoppable!",
    "Surrender or face our wrath!",
    "You cannot hide from the Pillagers!",
    "Every village will bow to us!",
    "Our crossbows never miss!",
    "The Iron Golem cannot protect you!",
    "We have a score to settle with villagers!",
    "Fear the banner of the Pillagers!",
    "You stumbled into the wrong raid!",
    "Run while your legs still work!",
    "The Evoker sends his regards!",
    "We have scouted your village already!",
    "The Pillager outpost grows stronger daily!",
    "Your Iron Golem cannot stop all of us!",
    "We will return with more soldiers!",
    "The captain has marked you as a target!",
  ],
  piglin: [
    "Gold! Give us your gold!",
    "You dare enter the Nether without gold?!",
    "Hand over the gold and nobody gets hurt!",
    "We smell no gold on you... attack!",
    "The Nether belongs to the Piglins!",
    "Your golden armor means nothing here!",
    "Bartering is the only law we follow!",
    "We protect our gold with our lives!",
    "No gold? No mercy!",
    "The Piglin king demands tribute!",
    "Intruder in our fortress!",
    "You cannot steal from the Piglins!",
    "We have claimed this bastion!",
    "Gold is life. Life is gold!",
    "Your kind does not belong here!",
    "Drop the gold and we may spare you!",
    "The Nether is no place for the weak!",
    "We have hunted in these halls for ages!",
    "Zombie Piglins will avenge us!",
    "No one leaves the Nether without our blessing!",
    "This gold ore belongs to the Piglins!",
    "We built this bastion with our own hands!",
    "Ancient debris is ours to claim!",
    "You smell like the Overworld. Leave now!",
    "Our hoglin army awaits your defeat!",
  ],
  witch: [
    "I have a potion with your name on it!",
    "My cauldron never runs dry!",
    "You should not have come here...",
    "Hehehehe... a visitor!",
    "I have been expecting you, fool.",
    "My potions will be your undoing!",
    "The swamp is mine and mine alone!",
    "I brew curses for those who trespass!",
    "Your health will drain before you know it!",
    "I learned my craft from the darkest texts!",
    "No hero has ever bested my brews!",
    "Slowness and poison, my favorites!",
    "My hut is off limits to outsiders!",
    "A splash potion for the intruder!",
    "I can smell your health from here!",
    "The swamp protects its own!",
    "I have brewed potions older than your village!",
    "Harming II is my specialty!",
    "You will regret disturbing my rituals!",
    "Hehehe... you walked right into my trap!",
    "My potions are older than your village!",
    "I learned from the great witch of the east!",
    "You will feel the effects shortly!",
    "My swamp hut is protected by dark magic!",
    "Even the rain obeys my command!",
  ],
};

// Get a random dialogue line for hostile type
export function getHostileDialogue(type) {
  const lines = hostileDialogue[type] ?? hostileDialogue.illager;
  return lines[Math.floor(Math.random() * lines.length)];
}